### ISSUE TITLE
File Could not be Imported! 'Illegal quoting'

### ISSUE THREAD

**Issue by cdmichaelb** [nikhgupta/swarlogs#22]
`File could not be imported!
Are you sure this is a valid CSV exported by SWProxy RunLogger?
Error encountered: CSV::MalformedCSVError: Illegal quoting in line 676.`

It appears to be HoH from april causing the issue.

`4/8/2016 14:05 10026 B1    Win 1:13    4925    0   3   Unknown drop {"mana": 2874   "energy": 1     "crystal": 0}`

**Comment by nikhgupta** [comment]
@cdmichaelb: I have already taken care of such logs - and they should be ignored (at the moment). Can you upload the CSV file somewhere for me to see/debug?

**Comment by cdmichaelb** [comment]
I'll see if I can find somewhere, it's too big for pastebin et al... but the line i quoted, I deleted it and the others from B1 (hoh), and then it uploaded fine.

**Comment by nikhgupta** [comment]
Already fixed (at version 66b74547eb2764bb3b39264d4b2abad8574413de).
Files uploaded by users are now uploaded on Github for easy debugging later.
